title: CSC413/2516 Métodos Numéricos para Ecuaciones Diferenciales Parciales (Winter 2026)
description: CSC413/2516-2023 course website
sitename: uoft-CSC413
baseurl: '2023'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - contents
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - vendor
  - vendor/bundle
markdown: kramdown

theme: jekyll-theme-cayman
