title: CM032 / 2026-I Métodos Numéricos para Ecuaciones Diferenciales Parciales
description: Página web del curso CM032 / 2026-I
sitename: CM032
baseurl: 'CM032.github.io'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - contents
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - vendor
  - vendor/bundle
markdown: kramdown

theme: jekyll-theme-cayman
